[tool.poetry]
name = "alphab-logging"
version = "0.1.0"
description = "Reusable logging package with structured logging, multiple handlers, and easy configuration"
authors = ["Alphab <info@alphab.dev>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "alphab_logging" }]

[tool.poetry.dependencies]
python = "^3.11"
structlog = "^23.2.0"
colorama = "^0.4.6"
python-json-logger = "^2.0.7"
rich = "^13.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
black = "^23.12.0"
flake8 = "^6.1.0"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py311']

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers"
testpaths = ["tests"]
