[tool.poetry]
name = "alphab-http-client"
version = "0.1.0"
description = "Simple, elegant HTTP client for Python with connection pooling and async support"
authors = ["Alphab <info@alphab.dev>"]
readme = "README.md"
packages = [{ include = "alphab_http_client" }]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.23.0"
pytest-cov = "^4.0.0"
black = "^23.0.0"
ruff = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 100
lint.select = ["E", "F", "I", "N", "W", "UP"]
lint.ignore = []

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
addopts = "--cov=alphab_http_client --cov-report=term-missing"
